### ISSUE TITLE
Use mainline go-ethereum

### ISSUE THREAD

**Issue by obscuren** [etherapis/etherapis#2]
For easy of installation we hardcoded all the import paths. Now that we're done with the gopher gala we should move back to go-ethereum HEAD and use normal import paths (though continue to use Godeps).

**Comment by karalabe** [comment]
By head you mean master or develop head? Maybe it would be worthwhile to use develop for now as we'll only pull in deps whenever deemed stable enough, we can probably get some fixes into develop that we discover through etherapis and as long as we're only running on the testnet I don't think being ultra-stable is a necessity.

Regarding godeps, it might be worthwhile to check out the official Go vendoring that's enabled by default from Go 1.6. It should be similar to the godeps vendored packages, just with native tooling support.

**Comment by obscuren** [comment]
`develop` of course. We'll need to keep `master` in a "workable" state

**Comment by obscuren** [comment]
I wouldn't mind trying Go's package censoring system.

**Comment by karalabe** [comment]
You really need to disable autocorrect :P

**Comment by obscuren** [comment]
haha, yup, you're right! **vendoring** obviously :D

**Comment by karalabe** [comment]
I think it actually might make more sense to use this. It's essentially godeps, but with native Go tool support. So go get should work, import paths will stay the same old ones. Win-win. https://tip.golang.org/cmd/go/#hdr-Vendor_Directories

**Comment by karalabe** [comment]
I've moved the dependencies over to Go vendoring in https://github.com/etherapis/etherapis/commit/54611b84f769e54fa946c98674f717b7a852c866

Using Go 1.5, the `GO15VENDOREXPERIMENT=1` env var needs to be set when issuing any go command against the etherapis repo. Using Go 1.6+, the stock commands work by default without any special settings being required.

I needed to make a few tiny modifications here and there in the etherapis codebase to make the whole thing buildable again (I checked my IPC modifications, not sure that I didn't break anything with the `filter.LogCallback`). When you have time, could you check if everything's still ok?
